" Save this file as .vimrc in your home directory
set background=dark
set backspace=2         " backspace in insert mode works like normal editor
syntax on               " syntax highlighting
filetype indent on      " activates indenting for files
set autoindent          " auto indenting
set number              " line numbers
colorscheme industry      " colorscheme desert
" set nobackup            " get rid of anoying ~file
" See Tabs vs Spaces https://stackoverflow.com/a/1878983
set tw=70               " wrap line as this column
set wrap                " activate wrapping
set tabstop=4           " The width of a TAB is set to 4.
                        " Still is is a \t. It is just that
                        " Vim will interpret it to be having
                        " a width of 4.
set softtabstop=0       " Sets the number of columns for a TAB
set expandtab           " Expand TABs to spaces
set shiftwidth=4        " Indents will have a width of 4
" set smarttab          " Enabling this will make the tab key
                        " (in insert mode) insert spaces or tabs
                        " to go to the next indent of the next
                        " tabstop when the cursor is at the
                        " beginning of a line (i.e. the only
                        " preceding characters are whitespace).